name: GilliardCore
version: ${project.version}
main: com.github.carthax08.gilliardcore.Main
authors: [ CarThax08 ]
description: Core plugin for Gilliard City RP
commands:
  verify:
    description: Verify your discord
    usage: /verify
  911:
    description: Send a message to emergency services
    usage: /911 [message]
  wantedlist:
    description: Open the wanted list
    usage: /wantedlist